package com.example.relay.common;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.example.relay.app.domain.App;
import com.example.relay.app.infrastructure.AppRepository;
import com.example.relay.attempt.domain.Attempt;
import com.example.relay.attempt.domain.AttemptStatus;
import com.example.relay.attempt.infrastructure.AttemptRepository;
import com.example.relay.delivery.domain.Delivery;
import com.example.relay.endpoint.domain.Endpoint;
import com.example.relay.endpoint.infrastructure.EndpointRepository;
import com.example.relay.environment.domain.Environment;
import com.example.relay.environment.infrastructure.EnvironmentRepository;
import com.example.relay.event.domain.Event;
import com.example.relay.event.infrastructure.EventRepository;
import com.example.relay.message.domain.Message;
import com.example.relay.message.infrastructure.MessageRepository;
import com.example.relay.subscription.domain.Subscription;
import com.example.relay.subscription.infrastructure.SubscriptionRepository;
import com.example.relay.user.domain.RefreshToken;
import com.example.relay.user.domain.User;
import com.example.relay.user.infrastructure.RefreshTokenRepository;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.List;
import java.util.UUID;
import com.example.relay.support.SharedPostgresContainer;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;
import org.springframework.data.domain.Limit;

/**
 * Executes every hand-written repository query against real PostgreSQL at least once.
 *
 * <p>
 * Before the project moved to PostgreSQL-only testing, every repository test ran on H2, which was materially more
 * permissive than Postgres — most importantly about bind parameters whose type it cannot infer. That gap once let a
 * hand-written attempts query ship completely broken on the database the application actually runs on, while the
 * suite stayed green. Semantics are covered elsewhere; the job here is narrower and complementary: prove each
 * hand-written statement is one PostgreSQL will accept and execute.
 *
 * <p>
 * Add a case here whenever a new {@code @Query} (native or JPQL) is written. Derived query methods are generated by
 * Hibernate for the active dialect and are far less exposed, but the natives in particular bypass dialect translation
 * entirely.
 */
@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
class RepositoryPostgresAuditTest implements SharedPostgresContainer {

    @Autowired
    private TestEntityManager testEntityManager;

    @Autowired
    private AttemptRepository attemptRepository;
    @Autowired
    private RefreshTokenRepository refreshTokenRepository;
    @Autowired
    private EventRepository eventRepository;
    @Autowired
    private SubscriptionRepository subscriptionRepository;
    @Autowired
    private EndpointRepository endpointRepository;
    @Autowired
    private MessageRepository messageRepository;
    @Autowired
    private AppRepository appRepository;
    @Autowired
    private EnvironmentRepository environmentRepository;

    private User user;
    private Environment environment;
    private App app;
    private Event event;
    private Endpoint endpoint;
    private Message message;
    private Delivery delivery;
    private Attempt attempt;

    @BeforeEach
    void setUp() throws Exception {
        user = new User("audit-" + UUID.randomUUID() + "@mail.com", "hash");
        environment = new Environment("Env", "Desc", user);
        app = new App("App", environment);
        event = new Event("audit.event", app);
        endpoint = new Endpoint("EP", "https://example.com/hook", "whsec_secret", app);
        message = new Message(app, event, new ObjectMapper().readTree("{\"a\":1}"));
        delivery = new Delivery(app, message, endpoint);
        attempt = new Attempt(app, message, endpoint, delivery, 1);

        testEntityManager.persistAndFlush(user);
        testEntityManager.persistAndFlush(environment);
        testEntityManager.persistAndFlush(app);
        testEntityManager.persistAndFlush(event);
        testEntityManager.persistAndFlush(endpoint);
        testEntityManager.persistAndFlush(message);
        testEntityManager.persistAndFlush(delivery);
        testEntityManager.persistAndFlush(attempt);
        testEntityManager.persistAndFlush(new Subscription(app, event, endpoint));
    }

    @Test
    void everyNativeAttemptQueryExecutesOnPostgres() {
        Instant now = Instant.now();
        Instant future = now.plus(1, ChronoUnit.DAYS);

        assertEquals(1, attemptRepository.claim(attempt.getId(), now));
        assertEquals(1, attemptRepository.resetStuck(attempt.getId(), future, now));
        assertEquals(1, attemptRepository.touchCreated(attempt.getId(), now));
        // resetScheduled needs a SCHEDULED row with next_retry_at set; 0 rows is a legitimate
        // result here - what is under test is that Postgres accepts and runs the statement.
        assertDoesNotThrow(() -> attemptRepository.resetScheduled(attempt.getId(), future, now));
        assertDoesNotThrow(() -> attemptRepository.touchDeadLetterCandidate(attempt.getId(), future, now));
        assertDoesNotThrow(() -> attemptRepository.claimDeadLetterNotification(attempt.getId(), now));
    }

    @Test
    void everyAttemptFinderExecutesOnPostgres() {
        Instant future = Instant.now().plus(1, ChronoUnit.DAYS);

        assertDoesNotThrow(
                () -> attemptRepository.findByStatusAndUpdatedAtBefore(AttemptStatus.CREATED, future, Limit.of(100)));
        assertDoesNotThrow(() -> attemptRepository.findByStatusAndNextRetryAtBefore(AttemptStatus.SCHEDULED, future,
                Limit.of(100)));
        assertDoesNotThrow(() -> attemptRepository.findByStatusAndDeadLetterNotifiedAtIsNullAndUpdatedAtBefore(
                AttemptStatus.DEAD, future, Limit.of(100)));
        assertTrue(attemptRepository
                .findByIdAndDeliveryIdAndAppIdAndAppEnvironmentIdAndAppEnvironmentUserId(attempt.getId(),
                        delivery.getId(), app.getId(), environment.getId(), user.getId())
                .isPresent());
    }

    @Test
    void everyNativeRefreshTokenQueryExecutesOnPostgres() {
        Instant now = Instant.now();
        RefreshToken token = new RefreshToken(user, "hash-" + UUID.randomUUID(), now.plus(30, ChronoUnit.DAYS), now);
        testEntityManager.persistAndFlush(token);

        assertTrue(refreshTokenRepository.findByTokenHash(token.getTokenHash()).isPresent());
        assertEquals(1, refreshTokenRepository.slide(token.getId(), now.plus(60, ChronoUnit.DAYS)));
        assertEquals(1, refreshTokenRepository.revokeByTokenHash(token.getTokenHash(), now));
        // Already revoked, so the guard legitimately matches nothing the second time.
        assertEquals(0, refreshTokenRepository.revokeAllByUserId(user.getId(), now));
    }

    @Test
    void everyOwnershipScopedJpqlQueryExecutesOnPostgres() {
        UUID appId = app.getId();
        UUID envId = environment.getId();
        UUID userId = user.getId();

        assertTrue(eventRepository.findByIdAndAppIdAndEnvironmentIdAndUserId(event.getId(), appId, envId, userId)
                .isPresent());
        assertTrue(endpointRepository.findByIdAndAppIdAndEnvironmentIdAndUserId(endpoint.getId(), appId, envId, userId)
                .isPresent());
        assertTrue(
                endpointRepository.findByNameAndAppIdAndEnvironmentIdAndUserId("EP", appId, envId, userId).isPresent());
        assertEquals(1, endpointRepository.findAllByAppIdAndEnvironmentIdAndUserId(appId, envId, userId).size());
        assertTrue(messageRepository.findByIdAndAppIdAndEnvironmentIdAndUserId(message.getId(), appId, envId, userId)
                .isPresent());
        assertTrue(appRepository.findByIdAndEnvironmentIdAndEnvironmentUserId(appId, envId, userId).isPresent());
        assertEquals(1, environmentRepository.findAllByUserId(userId).size());
    }

    @Test
    void everySubscriptionQueryExecutesOnPostgres() {
        UUID appId = app.getId();
        UUID envId = environment.getId();
        UUID userId = user.getId();

        assertEquals(1, subscriptionRepository.findAllByAppIdAndEnvironmentIdAndUserId(appId, envId, userId).size());
        assertEquals(1, subscriptionRepository
                .findAllByAppIdAndEnvironmentIdAndEndpointIdAndUserId(appId, envId, endpoint.getId(), userId).size());
        assertTrue(subscriptionRepository.findByAppIdAndEnvironmentIdAndEventIdAndEndpointIdAndUserId(appId, envId,
                event.getId(), endpoint.getId(), userId).isPresent());
        assertEquals(1, subscriptionRepository.countByAppIdAndEnvironmentIdAndEventIdAndUserId(appId, envId,
                event.getId(), userId));
        assertEquals(1, subscriptionRepository.findAllByEventIdAndEndpointActiveTrue(event.getId()).size());
        // The projection query - aliases mapped onto interface getters, and an IN clause.
        assertEquals(1, subscriptionRepository.countByEventIdIn(appId, envId, List.of(event.getId()), userId).size());
    }
}
